"""added file type in document table

Revision ID: 4d2baf5fb27e
Revises: c57f4d0fd73e
Create Date: 2025-12-13 21:31:56.348348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2baf5fb27e'
down_revision = 'c57f4d0fd73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
