"""Added salary and credit history to loan model

Revision ID: c57f4d0fd73e
Revises: 989c07821029
Create Date: 2025-12-13 17:53:44.909064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57f4d0fd73e'
down_revision = '989c07821029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_salary', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('credit_history', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_column('credit_history')
        batch_op.drop_column('monthly_salary')

    # ### end Alembic commands ###
